"""Init

Revision ID: 0e0604cabc11
Revises:
Create Date: 2020-07-08 14:43:06.679639 

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0604cabc11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poker_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=True),     
    sa.Column('round', sa.Integer(), nullable=True),       
    sa.Column('stage', sa.Integer(), nullable=True),       
    sa.Column('player_turn', sa.Integer(), nullable=True), 
    sa.Column('dealer_turn', sa.Integer(), nullable=True), 
    sa.Column('card_a', sa.Integer(), nullable=True),      
    sa.Column('card_b', sa.Integer(), nullable=True),      
    sa.Column('card_c', sa.Integer(), nullable=True),      
    sa.Column('card_d', sa.Integer(), nullable=True),      
    sa.Column('card_e', sa.Integer(), nullable=True),      
    sa.Column('cards_shown', sa.Integer(), nullable=True), 
    sa.Column('last_raise_player', sa.Integer(), nullable=True),
    sa.Column('last_raise_amount', sa.Integer(), nullable=True),
    sa.Column('min_raise', sa.Integer(), nullable=False),  
    sa.Column('starting_amount', sa.Integer(), nullable=False),
    sa.Column('allow_join_in_progress', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('rpg_manager_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('party_level', sa.Integer(), nullable=True), 
    sa.Column('money_ratio', sa.Integer(), nullable=True), 
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), 
nullable=False),
    sa.Column('last_read_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_code')
    )
    op.create_table('poker_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=255), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),    
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('money', sa.Integer(), nullable=True),       
    sa.Column('moneyInRound', sa.Integer(), nullable=True),    sa.Column('card_a', sa.Integer(), nullable=True),      
    sa.Column('card_b', sa.Integer(), nullable=True),      
    sa.ForeignKeyConstraint(['game_id'], ['poker_game.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_index(op.f('ix_poker_player_game_id'), 'poker_player', ['game_id'], unique=False)
    op.create_table('poker_pot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),    
    sa.Column('round', sa.Integer(), nullable=False),      
    sa.Column('amount', sa.Integer(), nullable=False),     
    sa.ForeignKeyConstraint(['game_id'], ['poker_game.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poker_pot_game_id'), 'poker_pot', ['game_id'], unique=False)
    op.create_table('rpg_manager_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),    sa.Column('name', sa.String(length=25), nullable=True),    sa.Column('role', sa.Enum('barbarian', 'bard', 'cleric', 'druid', 'fighter', 'monk', 'paladin', 'ranger', 'rogue', 'sorcerer', 'warlock', 'wizard', name='rpgmanagerclass'), 
nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),       
    sa.Column('items', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['rpg_manager_campaign.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpg_manager_character_campaign_id'), 'rpg_manager_character', ['campaign_id'], unique=False)
    op.create_table('poker_player_to_pot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),  
    sa.Column('pot_id', sa.Integer(), nullable=False),     
    sa.ForeignKeyConstraint(['player_id'], ['poker_player.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['pot_id'], ['poker_pot.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poker_player_to_pot_player_id'), 'poker_player_to_pot', ['player_id'], unique=False)     
    op.create_index(op.f('ix_poker_player_to_pot_pot_id'), 
'poker_player_to_pot', ['pot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poker_player_to_pot_pot_id'), table_name='poker_player_to_pot')
    op.drop_index(op.f('ix_poker_player_to_pot_player_id'), table_name='poker_player_to_pot')
    op.drop_table('poker_player_to_pot')
    op.drop_index(op.f('ix_rpg_manager_character_campaign_id'), table_name='rpg_manager_character')
    op.drop_table('rpg_manager_character')
    op.drop_index(op.f('ix_poker_pot_game_id'), table_name='poker_pot')
    op.drop_table('poker_pot')
    op.drop_index(op.f('ix_poker_player_game_id'), table_name='poker_player')
    op.drop_table('poker_player')
    op.drop_table('rpg_manager_campaign')
    op.drop_table('poker_game')
    op.drop_table('note')
    # ### end Alembic commands ###