"""Add notes field to rpg campaign

Revision ID: a073de423a5b
Revises: 0e0604cabc11
Create Date: 2020-07-08 14:07:08.724317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a073de423a5b'
down_revision = '0e0604cabc11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpg_manager_campaign', sa.Column('notes', sa.String(length=3000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpg_manager_campaign', 'notes')
    # ### end Alembic commands ###
