"""Add morning report tables

Revision ID: a2ddb4fc8001
Revises: a073de423a5b
Create Date: 2020-09-29 02:15:23.693244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ddb4fc8001'
down_revision = 'a073de423a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('good_morning_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string', sa.String(length=1000), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('good_morning_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_morn_temp', sa.Integer(), nullable=False),
    sa.Column('weather_day_temp', sa.Integer(), nullable=False),
    sa.Column('weather_eve_temp', sa.Integer(), nullable=False),
    sa.Column('weather_desc', sa.String(length=100), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_read_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('good_morning_report')
    op.drop_table('good_morning_message')
    # ### end Alembic commands ###
