"""fix report relationship

Revision ID: f4a49fd05e68
Revises: a2ddb4fc8001
Create Date: 2020-09-29 02:40:43.685741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a49fd05e68'
down_revision = 'a2ddb4fc8001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('good_morning_report', sa.Column('message_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_good_morning_report_message_id'), 'good_morning_report', ['message_id'], unique=False)
    op.create_foreign_key(None, 'good_morning_report', 'good_morning_message', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'good_morning_report', type_='foreignkey')
    op.drop_index(op.f('ix_good_morning_report_message_id'), table_name='good_morning_report')
    op.drop_column('good_morning_report', 'message_id')
    # ### end Alembic commands ###
